name = "KinematicCoordinateTransformations"
uuid = "730d3219-0a85-48f9-b699-9f31f8913d09"
authors = ["Ingraham, Daniel James (GRC-LTV0) <daniel.j.ingraham@nasa.gov>"]
version = "0.4.2"

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "1.8.2"
ConcreteStructs = "0.2.3"
StaticArrays = "1.5.12"
